name: Deploy to RunPod

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mcs-proxy-manager:latest

      - name: Deploy to RunPod
        run: |
          curl -X POST https://api.runpod.io/v2/pod/${{ secrets.RUNPOD_POD_ID }}/restart \
            -H "Authorization: Bearer ${{ secrets.RUNPOD_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "imageName": "${{ secrets.DOCKERHUB_USERNAME }}/mcs-proxy-manager:latest",
              "env": {
                "PORT": "3000"
              },
              "volumeMountPath": "/app/data"
            }'